# Generated by Django 5.2.5 on 2025-08-26 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='content',
            field=ckeditor.fields.RichTextField(default='thanks'),
        ),
        migrations.AddField(
            model_name='mission',
            name='content',
            field=ckeditor.fields.RichTextField(default='default'),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='default'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_author',
            field=ckeditor.fields.RichTextField(default='default'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=ckeditor.fields.RichTextField(default='default'),
        ),
    ]
