# Generated by Django 5.2.5 on 2025-10-06 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vistablog', '0002_acknowledgement_content_mission_content_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
